%YAML 1.1
---

cam0:
  T_cam_imu:
    - [-0.005587150418483014, 0.9996943843182883, -0.024081563750755475, 0.0780926086492463]
    - [0.9999549729622957, 0.005400643566805694, -0.007802890300436733, 0.0010778158260177407]
    - [-0.007670449672449096, -0.024124075351083935, -0.9996795452495162, 0.004325721939111074]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [-0.00558715,  0.99995497, -0.00767045, -0.00060827]
    - [ 0.99969438,  0.00540064, -0.02412408, -0.07797021]
    - [-0.02408156, -0.00780289, -0.99967955,  0.00621334]
    - [ 0.,          0.,          0.,          1.        ]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.012407004019950539, -0.06090546238916809, 0.07341877032233166, -0.026361410656071057]
  distortion_model: equidistant
  intrinsics: [574.8975263974625, 574.435756683178, 632.0006541642256, 347.5452660175513]
  resolution: [1280, 720]
  rostopic: /front_camera/left_raw/image_raw_grey
  timeshift_cam_imu: -0.011304282478534742
cam1:
  T_cam_imu:
    - [-0.011344664054957208, 0.9998763009801834, -0.010894096367551686, 0.0029411675554122108]
    - [0.9998665984358339, 0.011215175364862775, -0.011874559945107254, 0.0013494582102033185]
    - [-0.011750911872477485, -0.011027355971433771, -0.9998701483144921, 0.004953995894757748]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [-0.01134466,  0.9998666,  -0.01175091, -0.0012577 ]
    - [ 0.9998763,  0.01121518, -0.01102736, -0.00290131]
    - [-0.0108941, -0.01187456, -0.99987015,  0.00500142]
    - [ 0.,          0.,          0.,          1.        ]
  T_cn_cnm1:
    - [0.9998964543235355, -0.00585917228697248, -0.013143467249306146, -0.07508018484859005]
    - [0.005911300719850347, 0.9999748024581085, 0.00393077252792043, -0.00020696278018995652]
    - [0.01312010499277755, -0.004008060500832151, 0.9999058947200982, -0.0003915822446780347]
    - [0.0, 0.0, 0.0, 1.0]
  # T_cnm1_cn:
  #  - [[ 0.99989645  0.0059113   0.0131201 0.07507877]
  #     [-0.00585917  0.9999748  -0.00400806 -0.00023452]
  #     [-0.01314347  0.00393077  0.99990589 -0.00059446]
  #     [0. 0. 0. 1.]]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.010647949624713804, -0.04990748750388707, 0.05877909380310711, -0.0205315740825269]
  distortion_model: equidistant
  intrinsics: [574.0425091568196, 573.629827184158, 631.677817523376, 325.5681676926967]
  resolution: [1280, 720]
  rostopic: /front_camera/right_raw/image_raw_grey
  timeshift_cam_imu: -0.010929218507649656
