%YAML 1.1
---
File.version: "1.0"
Camera.type: "KannalaBrandt8"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 574.8975263974625
Camera1.fy: 574.435756683178
Camera1.cx: 632.0006541642256
Camera1.cy: 347.5452660175513

# Kannala-Brandt distortion parameters
Camera1.k1: 0.012407004019950539
Camera1.k2: -0.06090546238916809
Camera1.k3: 0.07341877032233166
Camera1.k4: -0.026361410656071057

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 574.0425091568196
Camera2.fy: 573.629827184158
Camera2.cx: 631.677817523376
Camera2.cy: 325.5681676926967

# Kannala-Brandt distortion parameters
Camera2.k1: 0.010647949624713804
Camera2.k2: -0.04990748750388707
Camera2.k3: 0.05877909380310711
Camera2.k4: -0.0205315740825269

# Transformation matrix from right camera to left camera
# Kalibr's T_cn_cnm1 is the inverse of that!
# T_cn_cnm1 was manually inversed then used below
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: 
    [0.99989645,  0.0059113,   0.0131201, 0.07507877,
    -0.00585917,  0.9999748,  -0.00400806, -0.00023452,
    -0.01314347,  0.00393077,  0.99990589, -0.00059446,
    0., 0., 0., 1.]

# Lapping area between images
Camera1.overlappingBegin: 0
Camera1.overlappingEnd: 719

Camera2.overlappingBegin: 0
Camera2.overlappingEnd: 719

# Camera resolution
Camera.width: 1280
Camera.height: 720

# Camera frames per second
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0

# Transformation from camera 0 to body-frame (imu)
# Kalibr's T_imu_cam
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: 
    [-0.00558715,  0.99995497, -0.00767045, -0.00060827,
      0.99969438,  0.00540064, -0.02412408, -0.07797021,
      -0.02408156, -0.00780289, -0.99967955,  0.00621334,
      0.,          0.,          0.,          1.        ]

# IMU noise
IMU.NoiseAcc:  0.005886
IMU.AccWalk:  0.005
IMU.NoiseGyro: 0.00174532925199
IMU.GyroWalk: 1.0e-05
IMU.Frequency: 200.0
IMU.InsertKFsWhenLost: 0
#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7
